spring:
  datasource:
    url: jdbc:mysql://happyside01.caai8osp7pur.ap-northeast-2.rds.amazonaws.com:3306/happiness_savings
    username: admin
    password: qwerasdf1!

  jpa:
    hibernate:
      ddl-auto: update
